# bloomery — an operating layer for local LLMs.
# Copyright (C) 2026 Brice Lancaster
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License, version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Commercial licensing is available as an alternative to the AGPL — see
# LICENSING.md.

"""One client session, one bloomery agent, and the bytes its KV holds.

bloomery APPENDS: `generate_from` starts at `kv_cache_seq_pos_max + 1` with
`AddBos::Never`. Re-sending a conversation would duplicate it into the cache,
so this class exists to send only what is new — and, per the spec's
2026-08-31 amendment, to do that WITHOUT re-rendering history, because the
template rewrites historical assistant turns and a re-render is therefore not
a prefix extension of what was actually sent.
"""


class Session:
    def __init__(self, agent_id: str, template, keep_reasoning: bool = True):
        self.agent_id = agent_id
        self.template = template
        self.keep_reasoning = keep_reasoning
        self._sent_messages: list[dict] = []
        self._open_assistant_turn = False

    @staticmethod
    def _is_extension(previous: list[dict], current: list[dict]) -> bool:
        if len(current) < len(previous):
            return False
        for old, new in zip(previous, current):
            if old.get("role") != new.get("role") or old.get("content") != new.get("content"):
                return False
        return True

    def next_delta(self, messages: list[dict], tools) -> tuple[str, bool]:
        """The bytes to send, and whether this was a reset.

        `was_reset` is True only when the client rewrote history rather than
        appending to it — never on the first turn of a session, which is
        simply the initial render.
        """
        messages = list(messages)
        had_history = bool(self._sent_messages)
        is_extension = had_history and self._is_extension(self._sent_messages, messages)

        if is_extension and self.keep_reasoning:
            new = messages[len(self._sent_messages):]
            opener = "<|im_end|>\n" if self._open_assistant_turn else ""
            delta = opener + self.template.render_turns(new) + self.template.GENERATION_SUFFIX
            self._sent_messages = messages
            self._open_assistant_turn = True
            return delta, False

        # Full render path. This is reached for three distinct reasons:
        #   - first turn of the session (had_history is False);
        #   - the client rewrote history rather than appending (a real
        #     divergence: is_extension is False despite had_history);
        #   - keep_reasoning=False on an otherwise-legitimate append (spec's
        #     option B: no reuse, by deliberate choice, not a divergence).
        # Only the middle case is a reset -- the client did something the
        # adapter cannot trust. The third case is the adapter choosing not
        # to reuse a resident KV it could have reused; that is not the
        # client's fault, so was_reset must stay False.
        delta = self.template.render_initial(messages, tools)
        self._sent_messages = messages
        self._open_assistant_turn = True
        was_reset = had_history and not is_extension
        return delta, was_reset

    def record_generation(self, raw: str) -> None:
        """The generated bytes are already in the KV; record that the
        assistant turn is open so the next delta closes it."""
        self._sent_messages = self._sent_messages + [{"role": "assistant", "content": raw}]
        self._open_assistant_turn = True
